# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo My first Personal Pipeline!
  displayName: 'Run a one-line script'

- script: npm ci
  displayName: 'Install dependencies'

- script: npm run lint
  displayName: 'Linting the app'

- script: npm run test
  displayName: 'Testing the app'

- script: npm run build
  displayName: 'Building the app'
    
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/build'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
- script: |
    npm install -g netlify-cli
    netlify deploy --prod --dir '$(Build.ArtifactStagingDirectory)'
  displayName: 'Netlify Deploy'
  env:
    NETLIFY_SITE_ID: $(site_id)
    NETLIFY_AUTH_TOKEN: $(auth_token)
